# typed: false
# frozen_string_literal: true

# This file is generated by the Browser Control release workflow. DO NOT EDIT.
class BrowserControl < Formula
  desc "Control an existing Chromium browser with trusted coding agents"
  homepage "https://github.com/anomalyco/browser-control"
  url "https://registry.npmjs.org/@opencode-ai/browser-control/-/browser-control-0.2.0.tgz"
  sha256 "a61b7dc6bbff93027d5f87c8c21ca01e4b49d5678bcbebfb094928319dfd4231"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  def caveats
    extension = opt_libexec/"lib/node_modules/@opencode-ai/browser-control/extension/dist"
    <<~EOS
      Load the Browser Control extension from:
        #{extension}

      In your Chromium-family browser, enable Developer mode, choose
      "Load unpacked", then select that directory.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/browser-control --version")
    assert_match "# Browser Control", shell_output("#{bin}/browser-control skill")
  end
end
