# typed: strict
# frozen_string_literal: true

# This file is generated by the OpenCode release pipeline. DO NOT EDIT.
class OpencodeAT2 < Formula
  desc "AI coding agent, built for the terminal"
  homepage "https://opencode.ai/v2"
  version "0.0.0-beta-17898"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://registry.npmjs.org/@opencode-ai/cli-darwin-x64/-/cli-darwin-x64-0.0.0-beta-17898.tgz"
      sha256 "36e41c6c32054e3d382841fcd5d3c23e4414fee214ab727e0eea545ad7f780fb"
    end
    if Hardware::CPU.arm?
      url "https://registry.npmjs.org/@opencode-ai/cli-darwin-arm64/-/cli-darwin-arm64-0.0.0-beta-17898.tgz"
      sha256 "bac1e9380f095161ff9530e893d2ecf68338f5f17d486d17d54a44e5c35c0120"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://registry.npmjs.org/@opencode-ai/cli-linux-x64/-/cli-linux-x64-0.0.0-beta-17898.tgz"
      sha256 "6083007e565a2b707011b993a35ab595138f3b4d10ed242c8ee315048cc09bca"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://registry.npmjs.org/@opencode-ai/cli-linux-arm64/-/cli-linux-arm64-0.0.0-beta-17898.tgz"
      sha256 "ac607dd5afa7c8f8673f8d339feaa6c834c3b484846ed15b763372beb6841043"
    end
  end

  def install
    bin.install "bin/opencode2"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/opencode2 --version")
  end
end
