# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/anomalyco/opencode"
  version "1.2.0"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anomalyco/opencode/releases/download/v1.2.0/opencode-darwin-x64.zip"
      sha256 "b591b6d0c8a5407d63a614aefb7f92f823b215b041db428a346ac2fb20cd13a4"

      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anomalyco/opencode/releases/download/v1.2.0/opencode-darwin-arm64.zip"
      sha256 "664e8d21219b84990e36d56d9e9ce9c500c612f13f5e7ee3eceaafeb30991d2b"

      def install
        bin.install "opencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/anomalyco/opencode/releases/download/v1.2.0/opencode-linux-x64.tar.gz"
      sha256 "771c51cab7c1e0b97a2bf18329c39360dd9c2945fdf4a6bdc511ffd800487f2b"
      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/anomalyco/opencode/releases/download/v1.2.0/opencode-linux-arm64.tar.gz"
      sha256 "b80c957889d6ef6eb87a43da8250447b74549b229da876b427b618f8937f4b06"
      def install
        bin.install "opencode"
      end
    end
  end
end

