# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sst < Formula
  desc ""
  homepage ""
  version "4.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anomalyco/sst/releases/download/4.1.0/sst-mac-x86_64.tar.gz"
      sha256 "0b4dfe357f939ca5a1e574acd43a9fa387644d39a8d9611822bf78526bf6bc03"

      define_method(:install) do
        bin.install "sst"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anomalyco/sst/releases/download/4.1.0/sst-mac-arm64.tar.gz"
      sha256 "01b2ca5afff79f7a21fce270ae53aabfa3a77487fa052ca5e798ff39686dc30b"

      define_method(:install) do
        bin.install "sst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anomalyco/sst/releases/download/4.1.0/sst-linux-x86_64.tar.gz"
      sha256 "6a695bdd0428b16ef7af205eace27113dc0301a9d8a57abf76077cde9cf4b501"
      define_method(:install) do
        bin.install "sst"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anomalyco/sst/releases/download/4.1.0/sst-linux-arm64.tar.gz"
      sha256 "55241cc262b8d2e0514f6ec7c1564ea30376db073f9130fe6cea8cc63639e693"
      define_method(:install) do
        bin.install "sst"
      end
    end
  end
end
